import { Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { CopyButton } from '../shared/EditorPanel'

type GitCommand = { category: string; name: string; command: string; description: string }
const group = (category: string, items: [string, string, string][]) => items.map(([name, command, description]) => ({ category, name, command, description }))
const commands: GitCommand[] = [
  ...group('仓库与配置', [['初始化仓库', 'git init', '在当前目录创建 Git 仓库'], ['克隆仓库', 'git clone <url>', '克隆远程仓库'], ['浅克隆', 'git clone --depth 1 <url>', '仅获取最近一次历史'], ['查看配置', 'git config --list --show-origin', '显示配置及来源'], ['设置用户名', 'git config --global user.name "Your Name"', '设置全局提交者名称'], ['设置邮箱', 'git config --global user.email "you@example.com"', '设置全局提交邮箱'], ['设置默认分支', 'git config --global init.defaultBranch main', '新仓库默认使用 main'], ['添加安全目录', 'git config --global --add safe.directory <path>', '信任指定工作目录']]),
  ...group('状态与暂存', [['查看状态', 'git status --short --branch', '紧凑显示分支和文件状态'], ['暂存文件', 'git add <file>', '暂存指定文件'], ['暂存全部', 'git add -A', '暂存新增、修改和删除'], ['交互暂存', 'git add -p', '按代码块选择暂存'], ['取消暂存', 'git restore --staged <file>', '保留工作区修改'], ['丢弃文件修改', 'git restore <file>', '恢复到暂存区版本'], ['查看暂存差异', 'git diff --staged', '查看即将提交的内容'], ['查看未暂存差异', 'git diff', '查看工作区修改']]),
  ...group('提交与历史', [['创建提交', 'git commit -m "message"', '提交暂存内容'], ['追加上次提交', 'git commit --amend', '修改最近提交'], ['仅修改提交信息', 'git commit --amend -m "new message"', '重写最近提交说明'], ['单行历史', 'git log --oneline --graph --decorate --all', '图形化查看全部分支'], ['查看文件历史', 'git log --follow -- <file>', '跨重命名跟踪文件'], ['查看提交详情', 'git show <commit>', '查看提交内容'], ['按作者筛选', 'git log --author="name"', '筛选作者提交'], ['按内容搜索', 'git log -S "keyword" --oneline', '查找增删关键字的提交']]),
  ...group('分支与合并', [['列出分支', 'git branch -vv', '显示本地分支和上游'], ['创建并切换', 'git switch -c <branch>', '基于当前提交创建分支'], ['切换分支', 'git switch <branch>', '切换现有分支'], ['重命名当前分支', 'git branch -m <new-name>', '修改当前分支名称'], ['删除本地分支', 'git branch -d <branch>', '仅删除已合并分支'], ['强制删除分支', 'git branch -D <branch>', '删除未合并分支'], ['合并分支', 'git merge <branch>', '将指定分支合入当前分支'], ['中止合并', 'git merge --abort', '返回合并前状态']]),
  ...group('远程协作', [['查看远程', 'git remote -v', '显示远程地址'], ['添加远程', 'git remote add origin <url>', '添加 origin'], ['获取远程', 'git fetch --all --prune', '更新引用并清理失效分支'], ['拉取变基', 'git pull --rebase', '拉取后将本地提交变基'], ['首次推送', 'git push -u origin <branch>', '推送并设置上游'], ['推送当前分支', 'git push', '推送到上游'], ['安全强推', 'git push --force-with-lease', '远程未变化时才强推'], ['删除远程分支', 'git push origin --delete <branch>', '删除远程分支']]),
  ...group('变基与拣选', [['变基到 main', 'git rebase main', '将当前分支提交移到 main 之后'], ['交互式变基', 'git rebase -i HEAD~5', '整理最近 5 个提交'], ['继续变基', 'git rebase --continue', '解决冲突后继续'], ['中止变基', 'git rebase --abort', '恢复变基前状态'], ['拣选提交', 'git cherry-pick <commit>', '应用指定提交'], ['拣选不提交', 'git cherry-pick -n <commit>', '应用改动但暂不提交'], ['继续拣选', 'git cherry-pick --continue', '解决冲突后继续'], ['中止拣选', 'git cherry-pick --abort', '恢复拣选前状态']]),
  ...group('储藏与恢复', [['储藏修改', 'git stash push -m "message"', '保存当前工作区和暂存区'], ['包含未跟踪文件', 'git stash push -u -m "message"', '同时储藏新文件'], ['查看储藏', 'git stash list', '列出储藏记录'], ['应用最近储藏', 'git stash pop', '应用并删除最近记录'], ['应用指定储藏', 'git stash apply stash@{1}', '保留储藏记录'], ['删除储藏', 'git stash drop stash@{0}', '删除指定记录'], ['恢复某次提交文件', 'git restore --source=<commit> <file>', '从历史恢复文件'], ['创建反向提交', 'git revert <commit>', '安全撤销已发布提交']]),
  ...group('标签与发布', [['列出标签', 'git tag --sort=-version:refname', '按版本倒序列出'], ['创建轻量标签', 'git tag v1.0.0', '标记当前提交'], ['创建附注标签', 'git tag -a v1.0.0 -m "release"', '创建带说明的标签'], ['推送标签', 'git push origin v1.0.0', '推送指定标签'], ['推送全部标签', 'git push --tags', '推送所有本地标签'], ['删除本地标签', 'git tag -d v1.0.0', '删除本地标签'], ['删除远程标签', 'git push origin :refs/tags/v1.0.0', '删除远程标签'], ['查看标签内容', 'git show v1.0.0', '显示标签指向内容']]),
  ...group('排查与维护', [['逐行追踪', 'git blame -L 10,30 <file>', '查看指定行的最后修改'], ['二分查错', 'git bisect start', '开始二分定位问题提交'], ['标记坏提交', 'git bisect bad', '标记当前提交有问题'], ['标记好提交', 'git bisect good <commit>', '标记已知正常提交'], ['结束二分', 'git bisect reset', '退出二分并恢复'], ['检查对象', 'git fsck --full', '检查仓库对象完整性'], ['清理预览', 'git clean -nd', '预览未跟踪文件清理范围'], ['压缩仓库', 'git gc --prune=now', '整理并清理不可达对象']]),
]
const categories = ['全部', ...new Set(commands.map((item) => item.category))]

export default function GitMemoPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('全部')
  const filtered = useMemo(() => commands.filter((item) => (category === '全部' || item.category === category) && `${item.name} ${item.command} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  return <div className="git-memo-tool"><div className="reference-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`搜索 ${commands.length} 条 Git 命令…`} /><span>{filtered.length} 条</span></div><div className="regex-category-strip">{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="git-command-list">{filtered.map((item) => <div key={`${item.category}-${item.name}`}><span>{item.category}</span><strong>{item.name}</strong><code>{item.command}</code><p>{item.description}</p><CopyButton value={item.command} /></div>)}</div><div className="status-line">危险操作未提供无保护的强制覆盖写法；执行前仍需确认当前分支和目标范围</div></div>
}
